version: "3.8"

services:
  telegram_bot:
    container_name: "${BOT_CONTAINER_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${API_PORT}:443
    expose:
      - 443
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: >
      sh -c "if [ '$SENDING_TYPE' = 'webhook' ]; then 
        # Use SSL
        uvicorn app.main:app --host 0.0.0.0 --port $API_PORT --ssl-keyfile privkey.pem --ssl-certfile fullchain.pem
      else
        uvicorn app.main:app --host 0.0.0.0 --port $API_PORT
      fi"
  redis:
    container_name: redis
    hostname: ${REDIS_HOST}
    image: redis:6.2-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:6379
